### ISSUE TITLE
Docs: add "Caveats" section to README

### ISSUE THREAD

**Issue by hab25** [pfgray/fish-completion-sync#1]
@pfgray, you mention [here](https://github.com/direnv/direnv/issues/443#issuecomment-1556212235):

> It's not perfect, but it's been working well for me so far

Could you please elaborate on the imperfections via a "Caveats" section?

**Comment by hab25** [comment]
Also, the README currently contains
> This plugin tries to alleviate this issue.

which seems to imply that it does not eliminate the issue; why not?

**Comment by pfgray** [comment]
Thanks for reaching out!

There are no real caveats to consider. It's been working well for me so far in all cases that I need it (i.e. just nix-direnv). There's been a couple of times that it has stopped working, which I haven't had time to pinpoint/debug... I'll add some documentation about how to turn on/off debugging to help in case it helps anyone
